version: "3"

services:
  # 前端服务
  ve-blog-naive:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ve-blog-naive:latest  # 设置新的镜像名称和标签
    container_name: ve-blog-naive
    restart: always
    ports:
      - "9420:80"
