name: Build and Deploy on Tag

on:
  push:
    tags:
      - 'v*'  # 监听所有以 v 开头的 tag，如 v1.0.0

# 添加权限配置
permissions:
  contents: read
  packages: write

# 设置环境变量
env:
  IMAGE_NAME: ve-blog-naive
  EXPOSE_PORT: 9420

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set variables
        id: vars
        run: |
          # 提取 tag 名称（移除 refs/tags/ 前缀）
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$IMAGE_TAG .
          docker tag ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$IMAGE_TAG ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$IMAGE_TAG
          docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Deploy image: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
            
            # 拉取最新的 Docker 镜像
            docker pull ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

            # 停止并删除旧的容器
            docker stop ${{ env.IMAGE_NAME }} || true && docker rm -f ${{ env.IMAGE_NAME }} || true
            
            # 运行新的容器
            docker run -d \
            --name ${{ env.IMAGE_NAME }} \
            --restart always \
            -p ${{ env.EXPOSE_PORT }}:80 \
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
